### ISSUE TITLE
How to start automatic screen recording

### ISSUE THREAD

**Issue by gvnramu** [0x006F/react-media-recorder#10]
Hi @0x006F  Thanks for the repo,

I want to start screen recording implicitly after component loaded 

What I  tried is `<button className="start" onClick={startRecording}>Start Recording</button>` after that in `componentDIdMount() {$('.start').click();}`. screen is recording but the problem is Screen share permission dialog is coming two times. I don't know what to do. Please help me

**Comment by 0x006F** [comment]
Hey @gvnramu,

First of all, don't mix `react` with `jQuery`. It'll have unexpected consequences, since, both of them works on two different concepts.  

From the snippet you provided, what can I see is that, you assigned the `onClick` handler to a button and tries to call it from `componentDidMount`. This isn't necessary nor recommended approach. If you want to record as soon as your component is loaded, then call the `startRecording` from the `componentDidMount` function. No need to attach it to a button, and call the dom event.

**Comment by gvnramu** [comment]
Thanks, Problem solved
