### ISSUE TITLE
Track not stopping

### ISSUE THREAD

**Issue by dfabreguette-ap** [0x006F/react-media-recorder#16]
Since 1.2.0 upgrade, it looks like stream tracks are not stopping, and the chrome red light is left on even after component unmount.
Does anyone have the same issue ?

I tried to stop the stream tracks through a "VideoPreview" function component with no success !

```
const VideoPreview = ({ stream, status}) => {
  const videoRef = useRef()

  useEffect(() => {
    if (videoRef.current && stream) {
      videoRef.current.srcObject = stream;
    }
    return () => {
      if (status == 'stopped') {
        stream.getTracks().forEach(track => track.stop())
        stream.getTracks().forEach(track => (track.enabled = false))
      }
    }
  }, [stream]);

  if (!stream)
    return null;

  return <video ref={videoRef} id="localVideo" className="video-preview" autoPlay muted/>;
};
```

Seems like there's a missing opened stream left unstopped somewhere... 
Would that be a bug on our side ?

**Comment by wmik** [comment]
Probably not a bug on your end.
Possible explanation #12

**Comment by 0x006F** [comment]
Hey @dfabreguette-ap a small patch have been landed via #17 . Can you please update it to the latest and check?  

Let me know.

**Comment by dfabreguette-ap** [comment]
Great ! I'll have a look into it and get back ! Thanks !

**Comment by dfabreguette-ap** [comment]
Works great ! I close the issue, thanks for quick response !

**Comment by andreybs11** [comment]
It is not fixed ❗ 

Use case: if the user "closes" the recorder **before starting to record**, then there is no way to stop **audio tracks** because `mediaRecorder.current = null` and `previewVideo` only contains video tracks (https://github.com/0x006F/react-media-recorder/blob/master/src/index.ts#L240).

Maybe consider providing a `stopAudio` render prop OR adding getters for `mediaRecorder` and `mediaStream`.

Thanks
