### ISSUE TITLE
H264 support

### ISSUE THREAD

**Issue by deevus** [0x006F/react-media-recorder#5]
I was hoping to use this for H264 recording support, however upon inspecting the code there's no way to pass any options when creating the `MediaRecorder`. 

The supported constraints from `getUserMedia` reports that h264 is not a supported `mimeType`, however `MediaRecorder.isTypeSupported('video/webm;codecs=H264')` return true. I think the solution is to provide the video codec to the `MediaRecorder` constructor. 

See here: https://gist.github.com/kkm/60ce3479ad35d923bbff6e4e8f5ae25c

Cheers

**Comment by giridharangm** [comment]
Hey @deevus thanks for the input. Much appreciated!

However, are you sure about Chrome's support for `h264`? [This is the list of supported codes in Chrome](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/fast/mediarecorder/MediaRecorder-isTypeSupported.html), and I didn't see `h264` in it.  

The gist you gave didn't work either.

**Comment by giridharangm** [comment]
>  it seems like an general improvement to support passing the `mimeType` option directly to the `MediaRecorder` constructor.  

I agree. But since we already have a `blobPropertyBag` option for setting the blob type (which will override whatever `mimeType` we gave to the `MediaRecorder` constructor). So the remaining options for the constructor are the audio / video bitrate. May be we could introduce new `prop`s to address these. What's your thought?  

BTW, were you able to get h264 video from Chrome? I'm on Chromium nightly, didn't work for me.

**Comment by deevus** [comment]
Yeah I'm using Chrome and it worked for me (Fedora 29).

It seems to me that the same sort of approach as `blobPropertyBag` would be fine. A prop such as `mediaRecorderOptions` would handle all cases if passed directly to the constructor.

**Comment by giridharangm** [comment]
+1 for `mediaRecorderOptions`.  

Can you share your working code? I want to know what I'm missing. All my video outputs are in vp8

**Comment by deevus** [comment]
https://codesandbox.io/s/n5y31723oj

Make sure to open the sandbox in its own window to get camera permissions.

**Comment by deevus** [comment]
I can make a PR if you want

**Comment by giridharangm** [comment]
Wow!.. Much appreciated! Thanks!  

[Be careful here](https://github.com/giridharangm/react-media-recorder/blob/10a967d96463892e3d5b51623e41d66c841d3761/src/index.js#L164) as we create `mediaBlob` using this `blobPropertyBag` which is passed down to the child.  

Sorry, been a bit busy with my full-time since last week. I also have a plan to refactor this.

**Comment by 0x006F** [comment]
Added ability to pass `mediaRecorderOptions` via c09f8327f863ba79699c8f7ba2eaa522942b55c6

**Comment by deevus** [comment]
I meant to come back to this but got busy :) Thanks

**Comment by 0x006F** [comment]
Yeah me too!. Sorry for the delay though. Thanks for the support! 👍
